export enum AnimalDictionary {
  SPECIES = 'SPECIES',
  STATUS = 'STATUS',
  MEDICINES = 'MEDICINES',
  TREATMENTS = 'TREATMENTS'
}

export enum AnimalStatus {
  FOR_ADOPTION = 'FOR_ADOPTION',
  ADOPTED = 'ADOPTED',
  DEAD = 'DEAD',
  QUARANTINE = 'QUARANTINE'
}
